name: check quality
on: [ push, pull_request ]

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: pmd/pmd-github-action@v1
        with:
          sourcePath: 'src/main/java'
          rulesets: 'https://raw.githubusercontent.com/apache/maven-pmd-plugin/maven-pmd-plugin-3.19.0/src/main/resources/rulesets/java/maven-pmd-plugin-default.xml'
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1
